apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-1
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kuber-1
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: http-server-1
  template:
    metadata:
      labels:
        app: http-server-1
    spec:
      containers:
      - name: kuber-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-1
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: http-server-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-alb
  namespace: {{ .Values.namespace.name }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # service must be of type "NodePort" or "LoadBalancer" to use instance mode
    alb.ingress.kubernetes.io/group.name: example-3.common
    alb.ingress.kubernetes.io/group.order: '1'
spec:
  ingressClassName: alb
  rules:
   - host: {{ .Values.hosts.app }}
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kuber-service-1
                port: 
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-appgw
  namespace: {{ .Values.namespace.name }}
annotations:
  annotations:
    appgw.ingress.kubernetes.io/health-probe-hostname: "127.0.0.1"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
    appgw.ingress.kubernetes.io/health-probe-path: "/"
    appgw.ingress.kubernetes.io/backend-protocol: http
spec:
  #ingressClassName: external-nginx  
  ingressClassName: azure-application-gateway
  rules:
    - host: {{ .Values.hosts.app }}
      http:
          paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: kuber-service-1
                  port: 
                    number: 80
